apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # ACME server URL for Let's Encrypt's prod environment
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    # REPLACE THIS with your actual email address
    email: chris.jam.mcgee@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable HTTP01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Optional: Staging issuer for testing
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # ACME server URL for Let's Encrypt's staging environment
    # Use this for testing to avoid rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: chris.jam.mcgee@gmail.com  # REPLACE THIS
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx